# Imports

In [1]:
import numpy as np

In [2]:
a = np.array([
    [[7,4,4,2,0],
    [2,8,0,0,0],
    [0,9,4,6,3],
    [3,7,4,6,9]],

    [[0,9,3,6,2],
    [8,8,5,6,0],
    [5,4,3,6,9],
    [2,9,2,9,1]],

    [[3,4,2,1,3],
    [5,4,8,5,4],
    [7,5,1,3,1],
    [3,9,9,0,3]]
    ])
a

array([[[7, 4, 4, 2, 0],
        [2, 8, 0, 0, 0],
        [0, 9, 4, 6, 3],
        [3, 7, 4, 6, 9]],

       [[0, 9, 3, 6, 2],
        [8, 8, 5, 6, 0],
        [5, 4, 3, 6, 9],
        [2, 9, 2, 9, 1]],

       [[3, 4, 2, 1, 3],
        [5, 4, 8, 5, 4],
        [7, 5, 1, 3, 1],
        [3, 9, 9, 0, 3]]])

In [3]:
a2 = np.array([
    [ # dim 3 (consisting of 3 tables, or surfaces)
        [ # dim 2 (a table)
            [7,4,4,2,0],
            [2,8,0,0,0],
            [0,9,4,6,3],
            [3,7,4,6,9],
            ],
        [ # dim 2 (a table)
            [0,9,3,6,2],
            [8,8,5,6,0],
            [5,4,3,6,9],
            [2,9,2,9,1],
            ],
        [ # dim 2 (a table)
            [3,4,2,1,3],
            [5,4,8,5,4],
            [7,5,1,3,1],
            [3,9,9,0,3]
            ]
        ],
    [ # dim 3 (consisting of 3 tables, or surfaces)
        [ # dim 2 (a table)
            [7,4,4,2,0],
            [2,8,0,0,0],
            [0,9,4,6,3],
            [3,7,4,6,9],
            ],
        [ # dim 2 (a table)
            [0,9,3,6,2],
            [8,8,5,6,0],
            [5,4,3,6,9],
            [2,9,2,9,1],
            ],
        [ # dim 2 (a table)
            [3,4,2,1,3],
            [5,4,8,5,4],
            [7,5,1,3,1],
            [3,9,9,0,3]
            ]
        ]
    ])

In [4]:
a2

array([[[[7, 4, 4, 2, 0],
         [2, 8, 0, 0, 0],
         [0, 9, 4, 6, 3],
         [3, 7, 4, 6, 9]],

        [[0, 9, 3, 6, 2],
         [8, 8, 5, 6, 0],
         [5, 4, 3, 6, 9],
         [2, 9, 2, 9, 1]],

        [[3, 4, 2, 1, 3],
         [5, 4, 8, 5, 4],
         [7, 5, 1, 3, 1],
         [3, 9, 9, 0, 3]]],


       [[[7, 4, 4, 2, 0],
         [2, 8, 0, 0, 0],
         [0, 9, 4, 6, 3],
         [3, 7, 4, 6, 9]],

        [[0, 9, 3, 6, 2],
         [8, 8, 5, 6, 0],
         [5, 4, 3, 6, 9],
         [2, 9, 2, 9, 1]],

        [[3, 4, 2, 1, 3],
         [5, 4, 8, 5, 4],
         [7, 5, 1, 3, 1],
         [3, 9, 9, 0, 3]]]])

# Indexing

In [5]:
a3 = a2[0][2][1][3]
a3

5

In [6]:
a2[0,1,1,2]

5

# Array Atributes

In [7]:
a2.ndim

4

quick note, remember that the "dimensions" of the numpy array are often referred to as an axis or axes; to disambiguate between the dimensionality of an array and the dimensionality of the data represented by the array. For instance, the array 'a'could represent three points, each lying within a four-dimensional space, but 'a' has only two “axes” 

In [8]:
a2.shape

(2, 3, 4, 5)

In [9]:
a2.size

120

In [10]:
np.linspace(1, 100, num=7)

array([  1. ,  17.5,  34. ,  50.5,  67. ,  83.5, 100. ])

In [11]:
a2.shape

(2, 3, 4, 5)

In [12]:
np.divide()

TypeError: divide() takes from 2 to 3 positional arguments but 0 were given

In [ ]:
np.copy()