In [19]:
import numpy as np
import tensorflow as tf
import pandas as pd

In [20]:
sentences = [
    ['I love my dog'],
    ['i love my cat'],
    ['i love my girlfriend'],
    ['do you love my girlfriend more than i do']
]
# instantiate layer vectorization layer
vectorize_layer = tf.keras.layers.TextVectorization()

# adapt; pass sentences var through it
vectorize_layer.adapt(sentences)

# view the vocab
vocabulary = vectorize_layer.get_vocabulary()
print(vocabulary)
for index, word in enumerate(vocabulary):
    print(index, word)

['', '[UNK]', 'my', 'love', 'i', 'girlfriend', 'do', 'you', 'than', 'more', 'dog', 'cat']
0 
1 [UNK]
2 my
3 love
4 i
5 girlfriend
6 do
7 you
8 than
9 more
10 dog
11 cat


In [21]:
# get the tensor forms of sequences
sequence1 = vectorize_layer(['i love my dog'])
sequence2 = vectorize_layer(['do you love my girlfriend more than i do'])
print(sequence1)
print(sequence2)

tf.Tensor([[ 4  3  2 10]], shape=(1, 4), dtype=int64)
tf.Tensor([[6 7 3 2 5 9 8 4 6]], shape=(1, 9), dtype=int64)


In [38]:
# get the tensor forms of many sequences
rand_article = ["I Return a copy of the string with leading characters removed. The chars argument is a string specifying the set of characters to be removed.",
"If omitted or None, the chars argument defaults to removing whitespace. The chars argument is not a prefix; rather, all combinations of its values are stripped:"]
sequence1 = vectorize_layer(sentences)
sequence2 = vectorize_layer(rand_article)
print(sequence1,'\n\n',sequence2)


tf.Tensor(
[[ 4  3  2 10  0  0  0  0  0]
 [ 4  3  2 11  0  0  0  0  0]
 [ 4  3  2  5  0  0  0  0  0]
 [ 6  7  3  2  5  9  8  4  6]], shape=(4, 9), dtype=int64) 

 tf.Tensor(
[[4 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]], shape=(2, 26), dtype=int64)


In [37]:
for index, word in enumerate(rand_article):
    print(index, word)

0 I Return a copy of the string with leading characters removed. The chars argument is a string specifying the set of characters to be removed.
1 If omitted or None, the chars argument defaults to removing whitespace. ' 'The chars argument is not a prefix; rather, all combinations of its values are stripped:


In [39]:
print(len(rand_article[0]))

141


In [40]:
print(len(rand_article[1]))

160
